apiVersion: v1
kind: Secret
metadata:
  name: customerservice-database-credentials
  labels:
    service: customerservice
    type: configuration
type: Opaque
data:
  database: Y3VzdG9tZXJz
  username: Y3VzdG9tZXJzZXJ2aWNl
  password: U29tZUdlbmVyYXRlZFBAc3N3MHJkIQ==
stringData:
  database.json: | 
    {
      "Database": {
        "Server": "customerservice-db",
        "Port": 3306,
        "Database": "customers",
        "Username": "customerservice",
        "Password": "SomeGeneratedP@ssw0rd!"
      }
    }  