apiVersion: v1
kind: Pod
metadata:
  name: customerservice-api
  labels:
    service: customerservice
    type: api
spec:
  containers:
  - name: customerservice-container
    image: anthonyhuebers/customerservice:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - name: database-credentials
      mountPath: "/app/credentials"
  volumes:
  - name: database-credentials
    secret:
      secretName: customerservice-database-credentials
      items:
      - key: database.json
        path: database.json

---  

apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: customerservice-api
spec:
  ports:
    - port: 80
  selector:
    service: customerservice
    type: api