apiVersion: v1
kind: Secret
metadata:
  name: customerservice-database-credentials
  labels:
    service: customerservice
    type: configuration
type: Opaque
data:
  database: Y3VzdG9tZXJz
  username: Y3VzdG9tZXJzZXJ2aWNl
  password: U29tZUdlbmVyYXRlZFBAc3N3MHJkIQ==
  database.json: ew0KICAiRGF0YWJhc2UiOiB7DQogICAgIlNlcnZlciI6ICJjdXN0b21lcnNlcnZpY2UtZGIiLA0KICAgICJQb3J0IjogMzMwNiwNCiAgICAiRGF0YWJhc2UiOiAiY3VzdG9tZXJzIiwNCiAgICAiVXNlcm5hbWUiOiAiY3VzdG9tZXJzZXJ2aWNlIiwNCiAgICAiUGFzc3dvcmQiOiAiU29tZUdlbmVyYXRlZFBAc3N3MHJkISINCiAgfQ0KfQ==