apiVersion: v1
kind: Pod
metadata:
  name: customerservice-db
  labels:
    service: customerservice
    type: db
spec:
  containers:
  - name: customerservice-database-container
    image: mysql
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "P@ssw0rd!" 
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: customerservice-database-credentials
          key: database
    - name: MYSQL_USER 
      valueFrom:
        secretKeyRef:
          name: customerservice-database-credentials
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: customerservice-database-credentials
          key: password
          
---  

kind: Service
apiVersion: v1
metadata:
  name: customerservice-db
spec:
  ports:
    - port: 3306
  selector:
    service: customerservice
    type: db
