apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: case-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /customerservice
        pathType: Prefix
        backend:
          service: 
            name: customerservice-api
            port: 
              number: 80